CREATE TABLE mysql_type_table (
    id                          INT NOT NULL,
    column_integer              INTEGER,
    column_int                  INT,
    column_smallint             SMALLINT,
    column_tinyint              TINYINT,
    column_mediumint            MEDIUMINT,
    column_bigint               BIGINT,
    column_decimal              DECIMAL,
    column_numeric              NUMERIC,
    column_float                FLOAT,
    column_double               DOUBLE,
    column_date                 DATE,
    column_datetime             DATETIME,
    column_timestamp            TIMESTAMP,
    column_time                 TIME,
    column_year                 YEAR,
    column_char                 CHAR,
    column_varchar              VARCHAR(16),
    column_text                 TEXT,
    column_enum                 ENUM('enum1', 'enum2', 'enum3'),
    column_json                 JSON,
    column_point                POINT,
    column_linestring           LINESTRING,
    column_polygon              POLYGON,
    column_multipoint           MULTIPOINT,
    column_multilinestring      MULTILINESTRING,
    column_multipolygon         MULTIPOLYGON,
    column_null                 INTEGER,
    PRIMARY KEY (id)
);

INSERT INTO mysql_type_table(
                            id,
                            column_integer,
                            column_int,
                            column_smallint,
                            column_tinyint,
                            column_mediumint,
                            column_bigint,
                            column_decimal,
                            column_numeric,
                            column_float,
                            column_double,
                            column_date,
                            column_datetime,
                            column_timestamp,
                            column_time,
                            column_year,
                            column_char,
                            column_varchar,
                            column_text,
                            column_enum,
                            column_json,
                            column_point,
                            column_linestring,
                            column_polygon,
                            column_multipoint,
                            column_multilinestring,
                            column_multipolygon,
                            column_null
                            )
VALUES (
        1,
        123,
        12345,
        1234,
        23,
        6897654,
        896932589235,
        7895.12,
        123123.4124124,
        124124124.12093091724124,
        21345.22,
        '9999-12-31',
        '9999-12-31 23:59:59',
        '1994-11-01 09:59:59',
        '00:11:12',
        2155,
        'c',
        'varchar',
        'text',
        'enum1',
        '[{"key": "Hello World !"}]',
        POINT(1, 3),
        LINESTRING(POINT(0, 0) , POINT(1, 2) , POINT(2, 4), POINT(3, 6)),
        POLYGON(LINESTRING(POINT(40, 40), POINT(48, 40), POINT(52, 49), POINT(40, 49), POINT(40, 40), POINT(45, 43), POINT(44, 45), POINT(47, 49), POINT(43, 47), POINT(40, 40))),
        MULTIPOINT(POINT(0, 0) , POINT(1, 2) , POINT(2, 4)),
        MULTILINESTRING(LINESTRING(POINT(12, 12), POINT(22, 22)), LINESTRING(POINT(19, 19), POINT(32, 18))),
        MULTIPOLYGON(POLYGON(LINESTRING(POINT(140, 140), POINT(148, 140), POINT(152, 149), POINT(140, 149), POINT(140, 140), POINT(145, 143), POINT(144, 145), POINT(147, 149), POINT(143, 147), POINT(140, 140)))),
        null
    );

CREATE TABLE IF NOT EXISTS table_test (
                                          id                          INT NOT NULL,
                                          criteria_number             INT,
                                          content                     VARCHAR(255),
                                          PRIMARY KEY (id)
);

INSERT INTO table_test (id, criteria_number, content) VALUES (1234, 0, 'content 1');
INSERT INTO table_test (id, criteria_number, content) VALUES (1235, 1, 'content 2');
INSERT INTO table_test (id, criteria_number, content) VALUES (1236, 2, 'content 3');
INSERT INTO table_test (id, criteria_number, content) VALUES (1237, 3, 'content 4');